title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: cooling-test    # the name of the repository when it is created for the learner
  repo: cooling-test-repo     # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond
  with: 01_first-response.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: EDIT HERE - INTERNAL COMMENT DESCRIBING STEP 
- title: test # the title of the step, shown to the learner in the course progress page
  description: test # a description of the step, shown to the learner in the course progress page
  event: issue_commented.created # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
  - title: test # the title of the step, shown to the learner in the course progress page
    description: test # a description of the step, shown to the learner in the course progress page
    event: issue_commented.created # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/

- title: Assign yourself
  description: Assign the first issue to yourself.
  event: issues.assigned
  link: 'https://github.com/QAInsights/lab-starter/issues/1'
  actions:
  - type: gate
    left: '%payload.pull_request.base.ref%'
    operator: ===
    right: master
    else:
    - type: respond
      with: 01_try-again.md
  - type: respond
    with: 01_nice-work.md
  
  #actions:
  #- type: gate
  # left: '%payload.pull_request.title%'
  # operator: ===
  # right: Add name to README
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions


# Step 3: EDIT HERE - INTERNAL COMMENT FOR STEP 3
 - title: test # the title of the step, shown to the learner in the course progress page
   description: test # a description of the step, shown to the learner in the course progress page
   event: issue_commented.created # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: EDIT HERE - INTERNAL COMMENT FOR STEP 4
  - title: test # the title of the step, shown to the learner in the course progress page
    description: test # a description of the step, shown to the learner in the course progress page
    event: issue_commented.created # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: EDIT HERE - INTERNAL COMMENT FOR STEP 5
  - title: test # the title of the step, shown to the learner in the course progress page
    description: test # a description of the step, shown to the learner in the course progress page
    event: issue_commented.created # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

